apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  labels:
    app.kubernetes.io/instance: <%- clusterName %>
    ops.kubeblocks.io/ops-type: HorizontalScaling
    sealos-db-provider-cr: <%- clusterName %>
  name: <%- name %>
  namespace: <%- namespace %>
  ownerReferences:
    - apiVersion: apps.kubeblocks.io/v1alpha1
      kind: Cluster
      name: <%- clusterName %>
      uid: <%- clusterUid %>
spec:
  clusterRef: <%- clusterName %>
  horizontalScaling:
    - componentName: mongodb
      replicas: <%- replicas %>
  type: HorizontalScaling
