apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    kb.io/database: mongodb-5.0
    app.kubernetes.io/instance: <%- name %>
    helm.sh/chart: mongodb-cluster-0.9.1
    sealaf-app: <%- label %>
  annotations: {}
  name: <%- name %>
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys:
      - kubernetes.io/hostname
  componentSpecs:
    - componentDef: mongodb
      monitor: true
      name: mongodb
      replicas: <%- replicas %>
      resources:
        limits:
          cpu: <%- limitCPU %>m
          memory: <%- limitMemory %>Mi
        requests:
          cpu: <%- requestCPU %>m
          memory: <%- requestMemory %>Mi
      serviceAccountName: laf-mongodb-<%- name %>
      serviceVersion: 5.0
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: <%- capacity %>Gi
  terminationPolicy: Delete
